name: Run BDD-Cucumber API Test Suite

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      suite:
        description: 'Cucumber tag to run (e.g., @smoke)'
        required: true
        default: '@sanity'
      username:
        description: 'Username to run the test'
        required: true
      password:
        description: 'Password to run the test'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (Corretto 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build and Run Tests
        run: |
          TAG="${{ github.event.inputs.suite }}"
          if [ -z "$TAG" ]; then
            echo "No tag provided. Using default: @sanity"
            TAG="@sanity"
          fi
          
          ENV="${{ github.event.inputs.env }}"
          if [ -z "$ENV" ]; then
            echo "No environment provided. Using default: local"
            ENV="local"
          fi

          echo "Running tests with tag: $TAG and environment: $ENV"
          
          mvn clean test \
            -Dcucumber.filter.tags="$TAG" \
            -Dusername="${{ github.event.inputs.username }}" \
            -Dpassword="${{ github.event.inputs.password }}" \
            -Denv="$ENV"


      - name: Upload ExtentSpark HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentSpark-Report
          path: target/Spark/ExtentSpark.html