name: Run BDD Test Suite

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      suite:
        description: 'Cucumber tag to run (e.g., @smoke)'
        required: true
        default: '@sanity'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (Corretto 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build and Run Tests
        run: |
          mvn clean test \
            -Dcucumber.filter.tags="${{ github.event.inputs.suite }}" \
            -Dusername=${{ secrets.USERNAME }} \
            -Dpassword=${{ secrets.PASSWORD }}

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/Spark/ExtentSpark.html